# Generated by Django 4.1 on 2022-12-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gametable', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spieltabelle',
            options={'verbose_name_plural': 'Spieltabelle Reihen'},
        ),
        migrations.AlterField(
            model_name='spieltabelle',
            name='streamlink',
            field=models.URLField(blank=True, max_length=512),
        ),
    ]
