# Generated by Django 4.1 on 2023-12-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gametable', '0002_alter_spieltabelle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spieltabelle',
            name='statslink',
            field=models.URLField(blank=True, max_length=512),
        ),
    ]
