# Generated by Django 4.1 on 2023-12-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gametable', '0003_spieltabelle_statslink'),
    ]

    operations = [
        migrations.AddField(
            model_name='spieltabelle',
            name='competition',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
