# Generated by Django 3.0 on 2020-12-13 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventinfo',
            options={'verbose_name_plural': 'Events'},
        ),
    ]
