# Generated by Django 3.0 on 2020-12-15 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20201213_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventinfo',
            name='friendly_name',
        ),
        migrations.RemoveField(
            model_name='eventinfo',
            name='name',
        ),
    ]
