# Generated by Django 3.0 on 2020-12-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20201215_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinfo',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
