# Generated by Django 3.0 on 2020-07-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200708_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsheadlines',
            name='paragraph2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='newsheadlines',
            name='paragraph3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='newsheadlines',
            name='paragraph4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='newsheadlines',
            name='paragraph5',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='newsheadlines',
            name='paragraph6',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='newsheadlines',
            name='paragraph7',
            field=models.TextField(default=''),
        ),
    ]
