# Generated by Django 3.0 on 2020-07-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200709_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsHeadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('heading', models.CharField(default='', max_length=254)),
                ('second_heading', models.CharField(blank=True, default='', max_length=254, null=True)),
                ('time_and_date_published', models.DateTimeField(default='')),
                ('paragraph1', models.TextField(default='')),
                ('paragraph2', models.TextField(default='')),
                ('paragraph3', models.TextField(default='')),
                ('paragraph4', models.TextField(default='')),
                ('paragraph5', models.TextField(default='')),
                ('paragraph6', models.TextField(default='')),
                ('paragraph7', models.TextField(default='')),
                ('paragraph8', models.TextField(default='')),
                ('paragraph9', models.TextField(default='')),
                ('paragraph10', models.TextField(default='')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='NewsHeadlines',
        ),
    ]
