# Generated by Django 3.0 on 2020-07-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200715_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsheadline',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='newsheadline',
            name='paragraph1',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='newsheadline',
            name='paragraph10',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='newsheadline',
            name='paragraph2',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='newsheadline',
            name='paragraph3',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='newsheadline',
            name='paragraph4',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='newsheadline',
            name='paragraph5',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='newsheadline',
            name='paragraph6',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='newsheadline',
            name='paragraph7',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='newsheadline',
            name='paragraph8',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='newsheadline',
            name='paragraph9',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
