# Generated by Django 3.0 on 2020-12-16 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200715_0706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsheadline',
            name='name',
        ),
    ]
