# Generated by Django 3.0 on 2020-12-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_remove_newsheadline_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsheadline',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
