# Generated by Django 3.0 on 2020-12-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20201217_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsheadline',
            name='friendly_name',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='newsheadline',
            name='paragraph1',
            field=models.TextField(default=''),
        ),
    ]
