# Generated by Django 3.0 on 2020-07-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='firstGalleryPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='', max_length=254)),
                ('image', models.ImageField(blank='False', null='False', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='galleryLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank='False', null='False', upload_to='')),
                ('heading', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='mainGalleryPageTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='secondGalleryPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='', max_length=254)),
                ('image', models.ImageField(blank='False', null='False', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='thirdGalleryPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='', max_length=254)),
                ('image', models.ImageField(blank='False', null='False', upload_to='')),
            ],
        ),
    ]
