# Generated by Django 3.0 on 2020-07-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firstgallerypage',
            old_name='image',
            new_name='image_row_1',
        ),
        migrations.RenameField(
            model_name='secondgallerypage',
            old_name='image',
            new_name='image_row_1',
        ),
        migrations.RenameField(
            model_name='thirdgallerypage',
            old_name='image',
            new_name='image_row_1',
        ),
        migrations.AddField(
            model_name='firstgallerypage',
            name='image_row_2',
            field=models.ImageField(blank='False', null='False', upload_to=''),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='firstgallerypage',
            name='image_row_3',
            field=models.ImageField(blank='False', null='False', upload_to=''),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='firstgallerypage',
            name='image_row_4',
            field=models.ImageField(blank='False', null='False', upload_to=''),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='secondgallerypage',
            name='image_row_2',
            field=models.ImageField(blank='False', null='False', upload_to=''),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='secondgallerypage',
            name='image_row_3',
            field=models.ImageField(blank='False', null='False', upload_to=''),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='secondgallerypage',
            name='image_row_4',
            field=models.ImageField(blank='False', null='False', upload_to=''),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='thirdgallerypage',
            name='image_row_2',
            field=models.ImageField(blank='False', null='False', upload_to=''),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='thirdgallerypage',
            name='image_row_3',
            field=models.ImageField(blank='False', null='False', upload_to=''),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='thirdgallerypage',
            name='image_row_4',
            field=models.ImageField(blank='False', null='False', upload_to=''),
            preserve_default='False',
        ),
    ]
