# Generated by Django 3.0 on 2020-07-10 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20200710_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firstgallerypage',
            old_name='image_row_1',
            new_name='image_column_1',
        ),
        migrations.RenameField(
            model_name='firstgallerypage',
            old_name='image_row_2',
            new_name='image_column_2',
        ),
        migrations.RenameField(
            model_name='firstgallerypage',
            old_name='image_row_3',
            new_name='image_column_3',
        ),
        migrations.RenameField(
            model_name='firstgallerypage',
            old_name='image_row_4',
            new_name='image_column_4',
        ),
        migrations.RenameField(
            model_name='secondgallerypage',
            old_name='image_row_1',
            new_name='image_column_1',
        ),
        migrations.RenameField(
            model_name='secondgallerypage',
            old_name='image_row_2',
            new_name='image_column_2',
        ),
        migrations.RenameField(
            model_name='secondgallerypage',
            old_name='image_row_3',
            new_name='image_column_3',
        ),
        migrations.RenameField(
            model_name='secondgallerypage',
            old_name='image_row_4',
            new_name='image_column_4',
        ),
        migrations.RenameField(
            model_name='thirdgallerypage',
            old_name='image_row_1',
            new_name='image_column_1',
        ),
        migrations.RenameField(
            model_name='thirdgallerypage',
            old_name='image_row_2',
            new_name='image_column_2',
        ),
        migrations.RenameField(
            model_name='thirdgallerypage',
            old_name='image_row_3',
            new_name='image_column_3',
        ),
        migrations.RenameField(
            model_name='thirdgallerypage',
            old_name='image_row_4',
            new_name='image_column_4',
        ),
    ]
