# Generated by Django 3.0 on 2020-07-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20200710_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='mainGalleryPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='', max_length=254)),
                ('image1', models.ImageField(blank='False', null='False', upload_to='')),
                ('heading1', models.CharField(default='', max_length=100)),
                ('image2', models.ImageField(blank='False', null='False', upload_to='')),
                ('heading2', models.CharField(default='', max_length=100)),
                ('image3', models.ImageField(blank='False', null='False', upload_to='')),
                ('heading3', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='galleryLinks',
        ),
        migrations.DeleteModel(
            name='mainGalleryPageTitle',
        ),
    ]
