# Generated by Django 3.0 on 2020-11-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20200711_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstgallerypagetitle',
            name='page_image',
            field=models.ImageField(blank='False', null='False', upload_to=''),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='secondgallerypagetitle',
            name='page_image',
            field=models.ImageField(blank='False', null='False', upload_to=''),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='thirdgallerypagetitle',
            name='page_image',
            field=models.ImageField(blank='False', null='False', upload_to=''),
            preserve_default='False',
        ),
    ]
