# Generated by Django 3.0 on 2020-12-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20201123_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstgallerypictures',
            name='friendly_name',
            field=models.CharField(default='', max_length=254),
        ),
    ]
