# Generated by Django 3.0 on 2020-12-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_auto_20201220_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstgallerypagetitle',
            name='page_image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='firstgallerypictures',
            name='image_column_1',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='firstgallerypictures',
            name='image_column_2',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='firstgallerypictures',
            name='image_column_3',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='firstgallerypictures',
            name='image_column_4',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='maingallerypage',
            name='image1',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='maingallerypage',
            name='image2',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='maingallerypage',
            name='image3',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='secondgallerypagetitle',
            name='page_image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='secondgallerypictures',
            name='image_column_1',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='secondgallerypictures',
            name='image_column_2',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='secondgallerypictures',
            name='image_column_3',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='secondgallerypictures',
            name='image_column_4',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='thirdgallerypagetitle',
            name='page_image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='thirdgallerypictures',
            name='image_column_1',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='thirdgallerypictures',
            name='image_column_2',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='thirdgallerypictures',
            name='image_column_3',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='thirdgallerypictures',
            name='image_column_4',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
