# Generated by Django 3.0 on 2020-09-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('addressLine1', models.CharField(default='', max_length=100)),
                ('addressLine2', models.CharField(default='', max_length=100)),
                ('addressLine3', models.CharField(default='', max_length=100)),
                ('addressLine4', models.CharField(default='', max_length=100)),
                ('phoneNumber', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
            ],
        ),
    ]
