# Generated by Django 3.0 on 2020-09-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='contactHeading',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='addressLine1',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='addressLine2',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='addressLine3',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='addressLine4',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phoneNumber',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
