# Generated by Django 3.0 on 2020-07-03 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empfehlung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('okkupation', models.CharField(max_length=60)),
                ('empfehlung_profil_bild', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Karte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('karten_bild', models.CharField(max_length=254)),
                ('karten_titel', models.CharField(max_length=40)),
                ('karten_beschreibung', models.CharField(max_length=254)),
                ('karten_knopf', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NewsLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_link_title', models.CharField(max_length=40)),
                ('link_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='StartseiteSektion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Startseite Sektionen',
            },
        ),
        migrations.CreateModel(
            name='SpielTabelle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teams', models.CharField(blank=True, max_length=60, null=True)),
                ('ort', models.CharField(blank=True, max_length=100, null=True)),
                ('datum', models.DateField(default='')),
                ('spielbeginn_zeit', models.TimeField(default='')),
                ('spielende_zeit', models.TimeField(default='')),
                ('startseite_sektion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.StartseiteSektion')),
            ],
            options={
                'verbose_name_plural': 'Spiel Tabelle Reihen',
            },
        ),
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bild', models.ImageField(upload_to='')),
                ('startseite_sektion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.StartseiteSektion')),
            ],
        ),
    ]
