# Generated by Django 3.0 on 2020-07-03 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spieltabelle',
            name='spielbeginn_zeit',
        ),
        migrations.RemoveField(
            model_name='spieltabelle',
            name='spielende_zeit',
        ),
    ]
