# Generated by Django 3.0 on 2020-07-03 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200703_1624'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BannerImage',
            new_name='BannerBild',
        ),
    ]
