# Generated by Django 3.0 on 2020-07-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200703_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerbild',
            name='banner_beschreibung',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='bannerbild',
            name='banner_titel',
            field=models.CharField(default='', max_length=50),
        ),
    ]
