# Generated by Django 3.0 on 2020-07-03 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200703_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newslink',
            old_name='news_link_title',
            new_name='news_link_titel',
        ),
    ]
