# Generated by Django 3.0 on 2020-07-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200703_2346'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsLink',
            new_name='NachrichtenLink',
        ),
        migrations.AlterModelOptions(
            name='bannerbild',
            options={'verbose_name_plural': 'Banner Bild (Startseite)'},
        ),
        migrations.AlterModelOptions(
            name='empfehlung',
            options={'verbose_name_plural': 'Empfehlungen'},
        ),
        migrations.AlterModelOptions(
            name='karte',
            options={'verbose_name_plural': 'Karten'},
        ),
        migrations.AlterModelOptions(
            name='nachrichtenlink',
            options={'verbose_name_plural': 'Nachrichten Links'},
        ),
        migrations.AlterField(
            model_name='karte',
            name='karten_bild',
            field=models.ImageField(upload_to=''),
        ),
    ]
