# Generated by Django 3.0 on 2020-07-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200704_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empfehlung',
            old_name='empfehlung_profil_bild',
            new_name='empfehler_profil_bild',
        ),
        migrations.AddField(
            model_name='empfehlung',
            name='zitat',
            field=models.CharField(default='', max_length=254),
        ),
    ]
