# Generated by Django 3.0 on 2020-07-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallToActionSektion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cta_bild', models.ImageField(upload_to='')),
                ('cta_knopf', models.CharField(default='', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Call To Action Sektion',
            },
        ),
        migrations.AlterModelOptions(
            name='sponsor',
            options={'verbose_name_plural': 'Sponsoren'},
        ),
    ]
