# Generated by Django 3.0 on 2020-07-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200704_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltoactionsektion',
            name='cta_knopf',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='karte',
            name='karten_knopf',
            field=models.CharField(max_length=40),
        ),
    ]
