# Generated by Django 4.1 on 2022-09-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20201220_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='spieltabelle',
            name='away',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='spieltabelle',
            name='home',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
