# Generated by Django 4.1 on 2023-11-11 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_spieltabelle_away_spieltabelle_home'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpielTabelle',
        ),
    ]
