# Generated by Django 4.1 on 2023-12-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_delete_spieltabelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='ordering',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
