# Generated by Django 4.1 on 2023-12-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_sponsor_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='karte',
            name='karten_ordering',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
