# Generated by Django 3.0 on 2020-07-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportshallinfo',
            name='description',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='sportshallinfo',
            name='descriptor',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
