# Generated by Django 3.0 on 2020-07-07 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20200707_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportshallinfo',
            name='training_day',
        ),
        migrations.RemoveField(
            model_name='sportshallinfo',
            name='training_time',
        ),
    ]
