# Generated by Django 3.0 on 2020-11-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20200707_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=40)),
                ('paragraph1', models.TextField(default='')),
                ('paragraph2', models.TextField(blank=True, default='', null=True)),
                ('paragraph3', models.TextField(blank=True, default='', null=True)),
                ('paragraph4', models.TextField(blank=True, default='', null=True)),
                ('paragraph5', models.TextField(blank=True, default='', null=True)),
                ('paragraph6', models.TextField(blank=True, default='', null=True)),
                ('paragraph7', models.TextField(blank=True, default='', null=True)),
                ('paragraph8', models.TextField(blank=True, default='', null=True)),
                ('paragraph9', models.TextField(blank=True, default='', null=True)),
                ('paragraph10', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
