# Generated by Django 3.0 on 2020-12-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanshop', '0002_bannerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='friendly_name',
            field=models.CharField(default='', max_length=254),
        ),
    ]
